spring:
  application:
    name: somnilingua
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:appdb}
    username: ${POSTGRES_USER:appuser}
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8082}
logging:
  level:
    org.flywaydb: DEBUG