spring:
  application:
    name: somnilingua
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB:appdb}
    username: ${POSTGRES_USER:appuser}
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: ${PORT:8080}
