const WALES = "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}";
const SCOTLAND = "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}";

export const LANGUAGE_FLAGS: Record<string, string> = {
    en: "🇬🇧",
    zh: "🇨🇳",
    hi: "🇮🇳",
    es: "🇪🇸",
    fr: "🇫🇷",
    ar: "🇸🇦",
    bn: "🇧🇩",
    pt: "🇵🇹",
    ru: "🇷🇺",
    ur: "🇵🇰",
    id: "🇮🇩",
    de: "🇩🇪",
    ja: "🇯🇵",
    sw: "🇰🇪",
    mr: "🇮🇳",
    te: "🇮🇳",
    tr: "🇹🇷",
    ta: "🇱🇰",
    vi: "🇻🇳",
    ko: "🇰🇷",
    it: "🇮🇹",
    th: "🇹🇭",
    gu: "🇮🇳",
    pl: "🇵🇱",
    uk: "🇺🇦",
    ml: "🇮🇳",
    kn: "🇮🇳",
    or: "🇮🇳",
    my: "🇲🇲",
    fa: "🇮🇷",
    ms: "🇲🇾",
    jv: "🇮🇩",
    ps: "🇦🇫",
    su: "🇮🇩",
    ha: "🇳🇬",
    pa: "🇮🇳",
    ro: "🇷🇴",
    nl: "🇳🇱",
    ig: "🇳🇬",
    yo: "🇳🇬",
    am: "🇪🇹",
    az: "🇦🇿",
    ceb: "🇵🇭",
    el: "🇬🇷",
    cs: "🇨🇿",
    sv: "🇸🇪",
    hu: "🇭🇺",
    fil: "🇵🇭",
    sd: "🇵🇰",
    si: "🇱🇰",
    so: "🇸🇴",
    km: "🇰🇭",
    uz: "🇺🇿",
    ku: "🇮🇶",
    zu: "🇿🇦",
    xh: "🇿🇦",
    he: "🇮🇱",
    lo: "🇱🇦",
    bg: "🇧🇬",
    sr: "🇷🇸",
    hr: "🇭🇷",
    sk: "🇸🇰",
    da: "🇩🇰",
    fi: "🇫🇮",
    no: "🇳🇴",
    lt: "🇱🇹",
    lv: "🇱🇻",
    et: "🇪🇪",
    sl: "🇸🇮",
    mk: "🇲🇰",
    sq: "🇦🇱",
    hy: "🇦🇲",
    ka: "🇬🇪",
    mn: "🇲🇳",
    ne: "🇳🇵",
    bo: "🇨🇳",
    cy: WALES,
    ga: "🇮🇪",
    gd: SCOTLAND,
    eu: "🇪🇸",
    ca: "🇪🇸",
    gl: "🇪🇸",
    af: "🇿🇦",
    sn: "🇿🇼",
    rw: "🇷🇼",
    rn: "🇧🇮",
    ln: "🇨🇩",
    ff: "🇸🇳",
    wo: "🇸🇳",
    bm: "🇲🇱",
    tw: "🇬🇭",
    ee: "🇬🇭",
    ny: "🇲🇼",
    mg: "🇲🇬",
    tl: "🇵🇭",
    ilo: "🇵🇭",
    hil: "🇵🇭",
    war: "🇵🇭",
    hmn: "🇱🇦",
    yue: "🇭🇰",
};

export const DEFAULT_LANGUAGE_FLAG = "🌐";

export function getLanguageFlag(code: string): string {
    return LANGUAGE_FLAGS[code.toLowerCase()] ?? DEFAULT_LANGUAGE_FLAG;
}
