import { getLanguageFlag } from "@/lib/language-flags";

export interface LangOption {
  code: string;
  name: string;
  flag: string;
}

const LANGUAGE_CATALOG: Omit<LangOption, "flag">[] = [
  { code: "en", name: "English" },
  { code: "zh", name: "Mandarin Chinese" },
  { code: "hi", name: "Hindi" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "ar", name: "Standard Arabic" },
  { code: "bn", name: "Bengali" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "ur", name: "Urdu" },
  { code: "id", name: "Indonesian" },
  { code: "de", name: "German" },
  { code: "ja", name: "Japanese" },
  { code: "sw", name: "Swahili" },
  { code: "mr", name: "Marathi" },
  { code: "te", name: "Telugu" },
  { code: "tr", name: "Turkish" },
  { code: "ta", name: "Tamil" },
  { code: "vi", name: "Vietnamese" },
  { code: "ko", name: "Korean" },
  { code: "it", name: "Italian" },
  { code: "th", name: "Thai" },
  { code: "gu", name: "Gujarati" },
  { code: "pl", name: "Polish" },
  { code: "uk", name: "Ukrainian" },
  { code: "ml", name: "Malayalam" },
  { code: "kn", name: "Kannada" },
  { code: "or", name: "Odia" },
  { code: "my", name: "Burmese" },
  { code: "fa", name: "Persian" },
  { code: "ms", name: "Malay" },
  { code: "jv", name: "Javanese" },
  { code: "ps", name: "Pashto" },
  { code: "su", name: "Sundanese" },
  { code: "ha", name: "Hausa" },
  { code: "pa", name: "Punjabi" },
  { code: "ro", name: "Romanian" },
  { code: "nl", name: "Dutch" },
  { code: "ig", name: "Igbo" },
  { code: "yo", name: "Yoruba" },
  { code: "am", name: "Amharic" },
  { code: "az", name: "Azerbaijani" },
  { code: "ceb", name: "Cebuano" },
  { code: "el", name: "Greek" },
  { code: "cs", name: "Czech" },
  { code: "sv", name: "Swedish" },
  { code: "hu", name: "Hungarian" },
  { code: "fil", name: "Filipino" },
  { code: "sd", name: "Sindhi" },
  { code: "si", name: "Sinhala" },
  { code: "so", name: "Somali" },
  { code: "km", name: "Khmer" },
  { code: "uz", name: "Uzbek" },
  { code: "ku", name: "Kurdish" },
  { code: "zu", name: "Zulu" },
  { code: "xh", name: "Xhosa" },
  { code: "he", name: "Hebrew" },
  { code: "lo", name: "Lao" },
  { code: "bg", name: "Bulgarian" },
  { code: "sr", name: "Serbian" },
  { code: "hr", name: "Croatian" },
  { code: "sk", name: "Slovak" },
  { code: "da", name: "Danish" },
  { code: "fi", name: "Finnish" },
  { code: "no", name: "Norwegian" },
  { code: "lt", name: "Lithuanian" },
  { code: "lv", name: "Latvian" },
  { code: "et", name: "Estonian" },
  { code: "sl", name: "Slovenian" },
  { code: "mk", name: "Macedonian" },
  { code: "sq", name: "Albanian" },
  { code: "hy", name: "Armenian" },
  { code: "ka", name: "Georgian" },
  { code: "mn", name: "Mongolian" },
  { code: "ne", name: "Nepali" },
  { code: "bo", name: "Tibetan" },
  { code: "cy", name: "Welsh" },
  { code: "ga", name: "Irish" },
  { code: "gd", name: "Scottish Gaelic" },
  { code: "eu", name: "Basque" },
  { code: "ca", name: "Catalan" },
  { code: "gl", name: "Galician" },
  { code: "af", name: "Afrikaans" },
  { code: "sn", name: "Shona" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "rn", name: "Kirundi" },
  { code: "ln", name: "Lingala" },
  { code: "ff", name: "Fulani" },
  { code: "wo", name: "Wolof" },
  { code: "bm", name: "Bambara" },
  { code: "tw", name: "Twi" },
  { code: "ee", name: "Ewe" },
  { code: "ny", name: "Chichewa" },
  { code: "mg", name: "Malagasy" },
  { code: "tl", name: "Tagalog" },
  { code: "ilo", name: "Ilocano" },
  { code: "hil", name: "Hiligaynon" },
  { code: "war", name: "Waray" },
  { code: "hmn", name: "Hmong" },
  { code: "yue", name: "Cantonese" },
];

export const LANGUAGE_OPTIONS: LangOption[] = LANGUAGE_CATALOG.map(({ code, name }) => ({
  code,
  name,
  flag: getLanguageFlag(code),
}));
